---
title: "Rio 2016 Olympics [Zehui Bai]"
author: Zehui Bai
date: 2025.07.27
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    theme: cerulean
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(ggforce)        
library(packcircles)
library(countrycode)
library(ggiraph)
library(plotly)
library(lubridate)
library(eeptools)
library(maps)
library(mapproj)
library(DT)

dat <- read_csv("Olympics_2016_Rio_Athletes.csv")

dat <- dat %>%
  mutate(country = case_when(
  nationality == 'IOA' ~ 'Independent Olympians',
  nationality == 'ISV' ~ 'United States Virgin Islands',
  nationality == 'LIB' ~ 'Lebanon',
  nationality == 'ROT' ~ 'Refugee Olympic Team',
  nationality == 'SIN' ~ 'Singapore',
  TRUE ~ countrycode(nationality, "ioc", "country.name")
  )) %>%
  mutate(continent = case_when(
  nationality == 'IOA' ~ 'Independent',
  nationality == 'ISV' ~ 'Americas',
  nationality == 'LIB' ~ 'Asia',
  nationality == 'ROT' ~ 'Independent',
  nationality == 'SIN' ~ 'Asia',
  nationality == 'KOS' ~ 'Europe',
  TRUE ~ countrycode(nationality, "ioc", "continent")
  )) %>%
  mutate(continent_id = case_when(
    continent == 'Americas' ~ 1,
    continent == 'Europe' ~ 2,
    continent == 'Asia' ~ 3,
    continent == 'Africa' ~ 4,
    continent == 'Oceania' ~ 5,
    continent ==  'Independent' ~ 6)) %>%
  mutate(total = gold + silver + bronze) %>%
  mutate(dob = date_of_birth)

cent <- function(x, year = 1940) {
  m <- year(x) %% 100
  y <- ifelse(m > year %% 100, 1900 + m, 2000 + m)
  update(x, year = y)
}

dob2 = as.tibble(cent(dat$dob))
dat <- dat %>%
  mutate(
    dob2 = cent(dob),
    age = floor(interval(start = dob2, end = mdy("08-05-2016")) /
                duration(n = 1, unit = "years"))
  )

sidebar_dat1 <- dat %>% filter(total > 0)
sidebar_dat2 <- dat %>% filter(total > 0)
```

Sidebar {.sidebar}
=====================================

```{r}
selectInput("my_medal", "Medals", choices = c("total", "gold", "silver", "bronze"), selected = "total")
selectInput("my_nationality", "Nationality", choices = sort(unique(sidebar_dat1$nationality)), selected = unique(sidebar_dat1$nationality), multiple = TRUE)
selectInput("my_sport", "Sport", choices = sort(unique(sidebar_dat1$sport)), selected = unique(sidebar_dat1$sport), multiple = TRUE)

selectInput("my_sex", "Sex", choices = c("female", "male"), selected = c("female", "male"), multiple = TRUE)
selectInput("my_sport2", "Sport", choices = sort(unique(sidebar_dat2$sport)), selected = unique(sidebar_dat2$sport), multiple = TRUE)
```


The athletes 
=====================================  

### Chart A

```{r, echo=FALSE, warning=FALSE}
renderUI({
  fig_dat1 <- dat %>% count(country, name = "number_of_athletes") %>%
    left_join(dat %>% select(nationality, country, continent_id) %>% distinct(), by = "country")
  packing <- circleProgressiveLayout(fig_dat1$number_of_athletes, sizetype = 'area')
  fig_dat1 <- bind_cols(fig_dat1, packing)
  dat.gg <- circleLayoutVertices(packing, npoints = 100)
  dat.gg$continent_id <- rep(fig_dat1$continent_id, each = 101)
  dat.gg$number_of_athletes <- rep(fig_dat1$number_of_athletes, each = 101)
  dat.gg$country <- rep(fig_dat1$country, each = 101)

  region_colors <- alpha(c(
    rgb(214,39,40, maxColorValue = 255),
    rgb(44,160,44, maxColorValue = 255),
    rgb(31,119,180, maxColorValue = 255),
    rgb(140,86,75, maxColorValue = 255),
    rgb(227,119,194, maxColorValue = 255),
    rgb(255,127,14, maxColorValue = 255)
  ), 0.75)


  gg1 <- ggplot(data = dat.gg) +
    ggiraph::geom_polygon_interactive(
      aes(x = x, y = y, group = id, fill = as.factor(continent_id),
          tooltip = paste0(country, "\nAthletes: ", number_of_athletes), data_id = x)) +
    scale_fill_manual(labels = c("Americas", "Europe", "Asia", "Africa", "Oceania", "Independent"),
                      values = region_colors) +
    labs(title = "Number of Athletes by Nationality & Region") +
    theme_void(base_size = 14) +
    theme(legend.position = "right",
          plot.title = element_text(hjust = 0.5, face = "bold", size = 24)) +
    coord_equal()

  girafe(ggobj = gg1, width_svg = 14, height_svg = 8)
})


```

### Chart B

```{r, echo=FALSE, warning=FALSE}
renderPlotly({
  req(input$my_nationality)
  world <- map_data("world") %>% rename("country" = "region") %>%
    mutate(nationality = countrycode(country, "country.name", "ioc"))
  fig_dat2 <- dat %>% filter(nationality %in% input$my_nationality) %>%
    count(country, name = "Athletes")
  world_combined <- left_join(world, fig_dat2, by = "country")
  gg <- ggplot(world_combined, aes(long, lat, group = group)) +
    geom_polygon(aes(fill = Athletes, text = country), color = "gray10") +
    scale_fill_viridis_c(na.value = "lightgray") +
    coord_map() + theme_void() +
    labs(title = "Global Distribution of Athletes")
  ggplotly(gg, tooltip = c("text", "fill"))
})
```
 
### Chart C

```{r}
renderPlotly({
  fig_dat3 <- dat %>%
    count(sex, name = "count") %>%
    mutate(per = count / sum(count))

  plot_ly(fig_dat3,
          labels = ~sex,
          values = ~per,
          type = 'pie',
          textinfo = 'label+percent',
          insidetextfont = list(size = 20),
          hoverinfo = 'text',
          text = ~paste(sex, "athletes:", count),
          marker = list(
            colors = c("rgba(214,39,40,0.75)", "rgba(31,119,180,0.75)"),
            line = list(color = '#000000', width = 2)
          )) %>%
    layout(
      title = "<b>Percentage of Athletes by Gender</b>",
      font = list(size = 14),
      legend = list(title = list(text = '<b>Sex</b>'))
    )
})
```

The medalists
=====================================  
 
 
 

### Chart D

```{r}
renderUI({
  req(input$my_medal, input$my_nationality, input$my_sport)

  fig_dat4 <- dat %>%
    select(nationality, sport, country, sex, !!as.symbol(input$my_medal)) %>%
    rename("medal" = input$my_medal) %>%
    filter(nationality %in% input$my_nationality,
           sport %in% input$my_sport) %>%
    group_by(country, sex, nationality) %>%
    summarise(medal = sum(medal, na.rm = TRUE), .groups = "drop") %>%
    filter(medal > 0)

  packing <- circleProgressiveLayout(fig_dat4$medal, sizetype = 'area')
  fig_dat4 <- bind_cols(fig_dat4, packing)
  dat.gg <- circleLayoutVertices(packing, npoints = 100)
  dat.gg$sex <- rep(fig_dat4$sex, each = 101)
  dat.gg$medal <- rep(fig_dat4$medal, each = 101)
  dat.gg$country <- rep(fig_dat4$country, each = 101)
  dat.gg$nationality <- rep(fig_dat4$nationality, each = 101)

  gg4 <- ggplot(dat.gg) +
    ggiraph::geom_polygon_interactive(
      aes(x = x, y = y, group = id, fill = sex,
          tooltip = paste0(country, " ", sex, " ", input$my_medal, " Medalists:\n", medal),
          data_id = x)) +
    scale_fill_manual(
      values = alpha(c("female" = rgb(214, 39, 40, max = 255), "male" = rgb(31, 119, 180, max = 255)), 0.75),
      labels = c("Female", "Male"),
      name = "Sex") +
    geom_text(data = filter(fig_dat4, medal > 5),
              aes(x = x, y = y, size = medal, label = nationality), color = "white") +
    scale_size(range = c(5, 9)) +
    labs(title = "Medals by Nationality and Sex") +
    theme_void(base_size = 14) +
    theme(legend.position = "right",
          legend.title = element_text(face = "bold", size = 22),
          legend.text = element_text(size = 20),
          plot.title = element_text(hjust = 0.5, size = 24, face = "bold")) +
    coord_equal()

  girafe(ggobj = gg4, width_svg = 16, height_svg = 10)
})
```


### Chart E

```{r}
renderPlotly({
  req(input$my_medal, input$my_nationality, input$my_sport)

  fig_dat5 <- dat %>%
    select(name, nationality, country, sport, sex, height, weight, !!as.symbol(input$my_medal)) %>%
    rename("medal" = input$my_medal) %>%
    filter(nationality %in% input$my_nationality,
           sport %in% input$my_sport,
           medal > 0)

  gg5 <- ggplot(fig_dat5, aes(x = weight, y = height, fill = sex, size = medal,
                              text = paste("Name:", name, "\nSex:", sex, "\nCountry:", country,
                                           "\nHeight:", height, "m\nWeight:", weight, "kg\n",
                                           input$my_medal, "medals:", medal))) +
    geom_jitter() +
    labs(title = "<b> Medalists by height vs. weight & sex <b>", x = "Weight (kg)", y = "Height (m)") +
    scale_fill_manual(values = alpha(c(rgb(214,39,40,max=255), rgb(31,119,180,max=255)), 0.5), name = "") +
    scale_size_continuous(range = c(3, 10), name = "") +
    theme_light() +
    ylim(1.4, 2.2) +
    xlim(30, 160)

  ggplotly(gg5, tooltip = c("text")) %>% layout(legend = list(title = list(text = "<b>Sex</b>")))
})
```
  

### Chart F

```{r}
renderPlotly({
  req(input$my_medal, input$my_nationality, input$my_sport)

  fig_dat6 <- dat %>%
    filter(nationality %in% input$my_nationality, sport %in% input$my_sport) %>%
    group_by(sport) %>%
    summarise(across(c(gold, silver, bronze, total), sum, na.rm = TRUE), .groups = "drop") %>%
    pivot_longer(cols = c(gold, silver, bronze), names_to = "medal", values_to = "count")

  if (input$my_medal != "total") {
    fig_dat6 <- fig_dat6 %>% filter(medal == input$my_medal)
  }

  my_fill <- switch(input$my_medal,
                    "gold" = c(alpha("gold")),
                    "silver" = c(alpha("grey")),
                    "bronze" = c(alpha(rgb(0.804, 0.498, 0.196))),
                    c(alpha("gold"), alpha("grey"), alpha(rgb(0.804, 0.498, 0.196))))

  gg6 <- ggplot(fig_dat6, aes(x = reorder(sport, -count), y = count, fill = medal,
                              text = paste(count, medal, "medalists"))) +
    geom_bar(stat = "identity") +
    labs(x = "Sport", y = "Medals", title = "<b> Medals awarded by sport <b>") +
    scale_fill_manual(values = my_fill) +
    theme_bw() +
    theme(panel.grid.major.x = element_blank(),
          panel.grid.major.y = element_line(size = .1, color = "darkgrey"),
          axis.text.x = element_text(size = 6))

  ggplotly(gg6, tooltip = c("text")) %>% hide_legend()
})
```


Attributes 
=====================================  
 
 

### Chart G

```{r}
renderPlotly({
  req(input$my_sex, input$my_sport2)

  fig_dat7 <- dat %>%
    filter(sex %in% input$my_sex, sport %in% input$my_sport2) %>%
    select(sex, sport, weight, height, age, total) %>%
    rename(weight_kg = weight, height_m = height, age_years = age) %>%
    pivot_longer(cols = c(weight_kg, height_m, age_years), names_to = "variable", values_to = "metric") %>%
    group_by(variable, metric) %>% summarise(total = sum(total, na.rm = TRUE), .groups = "drop")

  gg7 <- ggplot(fig_dat7, aes(x = metric, y = total, fill = variable,
                              text = paste0(variable, ": ", metric, "\nmedalists: ", total))) +
    geom_area() + geom_point() +
    facet_wrap(~variable, scales = "free") +
    labs(title = "<b> Distribution of medalists by weight, height & age <b>", x = "", y = "Medals") +
    scale_fill_manual(values = c(rgb(255,187,120,max=255), rgb(152,223,138,max=255), rgb(174,199,232,max=255))) +
    theme_light() +
    theme(plot.title = element_text(size = 20, face = "bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          strip.background = element_rect(color = "black", size = 1))

  ggplotly(gg7, tooltip = c("text")) %>% hide_legend() %>% layout(margin = list(t = 100))
})
```
 

### Chart H

```{r}
renderPlotly({
  req(input$my_sex, input$my_sport2)

  fig_dat8 <- dat %>%
    filter(sex %in% input$my_sex, sport %in% input$my_sport2, total > 0) %>%
    select(sex, sport, weight, height, age, total) %>%
    rename(weight_kg = weight, height_m = height, age_years = age) %>%
    pivot_longer(cols = c(weight_kg, height_m, age_years), names_to = "variable", values_to = "metric")

  gg8 <- ggplot(fig_dat8, aes(x = as.factor(variable), y = metric, fill = variable)) +
    geom_boxplot() +
    facet_wrap(~variable, scales = "free") +
    labs(title = "<b> Spread of medalists by weight, height & age <b>", x = "", y = "") +
    scale_fill_manual(values = c(rgb(255,187,120,max=255), rgb(152,223,138,max=255), rgb(174,199,232,max=255))) +
    theme_light() +
    theme(axis.text.x = element_blank(),
          plot.title = element_text(size = 20, face = "bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          strip.background = element_rect(color = "black", size = 1))

  ggplotly(gg8) %>% hide_legend() %>% layout(margin = list(t = 100))
})
```


Medals Table 
=====================================  

### Medals Table


```{r}
renderDataTable({
  fig_dat9 <- dat %>%
    select(country, gold, silver, bronze, total) %>%
    group_by(country) %>%
    summarise(across(c(gold, silver, bronze, total), sum, na.rm = TRUE), .groups = "drop") %>%
    arrange(desc(total))
  datatable(fig_dat9, options = list(pageLength = 10))
})
```

